import * as Blockly from 'blockly';
import 'blockly/blocks';

export function registerScratchBlocks(): void {
  if (Blockly.Blocks.event_when_green_flag) {
    return;
  }

  Blockly.defineBlocksWithJsonArray([
    {
      type: 'event_when_green_flag',
      message0: 'when green flag clicked',
      nextStatement: null,
      colour: '#F59E0B',
      tooltip: 'Start this stack when the green flag button is clicked.',
    },
    {
      type: 'event_when_sprite_clicked',
      message0: 'when this sprite clicked',
      nextStatement: null,
      colour: '#F59E0B',
      tooltip: 'Start this stack when the sprite is clicked on the stage.',
    },
    {
      type: 'event_when_key_pressed',
      message0: 'when key %1 pressed',
      args0: [
        {
          type: 'field_dropdown',
          name: 'KEY',
          options: [
            ['space', 'Space'],
            ['up arrow', 'ArrowUp'],
            ['down arrow', 'ArrowDown'],
            ['left arrow', 'ArrowLeft'],
            ['right arrow', 'ArrowRight'],
            ['a', 'a'],
            ['b', 'b'],
          ],
        },
      ],
      nextStatement: null,
      colour: '#F59E0B',
      tooltip: 'Start this stack when a keyboard key is pressed.',
    },
    {
      type: 'motion_move_steps',
      message0: 'move %1 steps',
      args0: [{ type: 'field_number', name: 'STEPS', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Move the sprite in the direction it is facing.',
    },
    {
      type: 'motion_turn_degrees',
      message0: 'turn %1 degrees',
      args0: [{ type: 'field_number', name: 'DEGREES', value: 15 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Turn the sprite clockwise.',
    },
    {
      type: 'motion_goto_xy',
      message0: 'go to x %1 y %2',
      args0: [
        { type: 'field_number', name: 'X', value: 0 },
        { type: 'field_number', name: 'Y', value: 0 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Move the sprite to an exact stage position.',
    },
    {
      type: 'motion_change_x',
      message0: 'change x by %1',
      args0: [{ type: 'field_number', name: 'DX', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Move the sprite left or right.',
    },
    {
      type: 'motion_change_y',
      message0: 'change y by %1',
      args0: [{ type: 'field_number', name: 'DY', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Move the sprite up or down.',
    },
    {
      type: 'motion_set_x',
      message0: 'set x to %1',
      args0: [{ type: 'field_number', name: 'X', value: 0 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Place the sprite at a horizontal position.',
    },
    {
      type: 'motion_set_y',
      message0: 'set y to %1',
      args0: [{ type: 'field_number', name: 'Y', value: 0 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Place the sprite at a vertical position.',
    },
    {
      type: 'motion_point_direction',
      message0: 'point in direction %1',
      args0: [{ type: 'field_angle', name: 'DIRECTION', angle: 90 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Choose which way the sprite faces.',
    },
    {
      type: 'motion_if_edge_bounce',
      message0: 'if on edge, bounce',
      previousStatement: null,
      nextStatement: null,
      colour: '#2563EB',
      tooltip: 'Bounce the sprite when it touches the stage edge.',
    },
    {
      type: 'looks_say_seconds',
      message0: 'say %1 for %2 seconds',
      args0: [
        { type: 'field_input', name: 'MESSAGE', text: 'Hello!' },
        { type: 'field_number', name: 'SECONDS', value: 2, min: 0 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Show a speech bubble above the sprite.',
    },
    {
      type: 'looks_think_seconds',
      message0: 'think %1 for %2 seconds',
      args0: [
        { type: 'field_input', name: 'MESSAGE', text: 'Hmm...' },
        { type: 'field_number', name: 'SECONDS', value: 2, min: 0 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Show a thought bubble above the sprite.',
    },
    {
      type: 'looks_show',
      message0: 'show',
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Make the sprite visible.',
    },
    {
      type: 'looks_hide',
      message0: 'hide',
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Make the sprite invisible.',
    },
    {
      type: 'looks_change_size',
      message0: 'change size by %1',
      args0: [{ type: 'field_number', name: 'AMOUNT', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Make the sprite bigger or smaller.',
    },
    {
      type: 'looks_set_size',
      message0: 'set size to %1 %',
      args0: [{ type: 'field_number', name: 'SIZE', value: 100, min: 5 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#7C3AED',
      tooltip: 'Choose the sprite size.',
    },
    {
      type: 'sound_play',
      message0: 'play sound %1',
      args0: [{ type: 'field_input', name: 'SOUND', text: 'pop' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#DB2777',
      tooltip: 'Play one of this sprite sound files.',
    },
    {
      type: 'sound_stop_all',
      message0: 'stop all sounds',
      previousStatement: null,
      nextStatement: null,
      colour: '#DB2777',
      tooltip: 'Stop sounds that are playing.',
    },
    {
      type: 'control_wait',
      message0: 'wait %1 seconds',
      args0: [{ type: 'field_number', name: 'SECONDS', value: 1, min: 0 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#EA580C',
      tooltip: 'Pause this script for a short time.',
    },
    {
      type: 'control_repeat',
      message0: 'repeat %1 times',
      args0: [{ type: 'field_number', name: 'TIMES', value: 10, min: 0 }],
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#EA580C',
      tooltip: 'Run the blocks inside more than once.',
    },
    {
      type: 'control_forever',
      message0: 'forever',
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#EA580C',
      tooltip: 'Keep running the blocks inside until stop is clicked.',
    },
  ]);
}
